name: Continuous Integration
on:
  push:
    tags:
      - '!v*'

jobs:
  build:
    name: Build and Unit test
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - run: yarn --frozen-lockfile
      - run: yarn build
      - run: yarn test
