name: Continuous Integration

on: [push]

jobs:
  build:
    name: Build and Unit test
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'
      - run: npm ci
      - run: npm run build
      - run: npm test
